### ISSUE TITLE
請問會不會提供puppeteer 爬取資料的code (放在github上)? 

### ISSUE THREAD

**Issue by mazecate** [WeiYun0912/pokemon-scarlet-and-violet-ev-list#1]
請問會不會提供puppeteer 爬取資料的code (放在github上)? 
Thanks.

**Comment by WeiYun0912** [comment]
可以，但因為這份 code 只有一開始的時候去使用到，所以後續優化的部份就沒有那麼注重。

[程式碼](https://gist.github.com/WeiYun0912/e793b85945cbe386c392b69c78650d72)

**Comment by WeiYun0912** [comment]
帕底亞地區的[寶可夢英文名字清單](https://gist.github.com/WeiYun0912/8829d1a8fc78a35b7ba118c438ce54dc)也順便給你

**Comment by WeiYun0912** [comment]
但如果用這份清單去爬的話，會有空白和特殊字元的問題，問題有寫在程式碼裡面了，你可以看要不要處理看看，應該不難。

**Comment by WeiYun0912** [comment]
如果需要 csv 檔的話再跟我說

**Comment by mazecate** [comment]
好的，感謝分享讓小弟也學習用puppeteer
